### ISSUE TITLE
Exit the game by pressing Back

### ISSUE THREAD

**Issue by outfrost** [outfrost/deckswipe#9]
Make the game exit after one or more presses of the Back button.

**Comment by stormofice** [comment]
This was already fixed by adding the following lines to `Game.cs`
```csharp
// Listen for Escape key ('Back' on Android) to quit the game
inputDispatcher.AddKeyDownHandler(KeyCode.Escape,
	keyCode => Application.Quit());
```
https://github.com/outfrost/deckswipe/blob/master/DeckSwipe/Assets/DeckSwipe/Game.cs#L33

**Comment by outfrost** [comment]
Yes. It's still open under "To Be Revisited" in the project, as a note to myself that maybe this should interoperate a bit better with Android, e.g. not terminate the app on Back, but background it instead. See also #26.
